name: auto-generate-gitbook
on:                                 #在 gitbook 分支上进行push时触发  
  push:
    branches:
    - gitbook

jobs:
  gitbook-to-main:
    runs-on: ubuntu-latest
        
    steps:                          
    - name: checkout gitbook
      uses: actions/checkout@v2
      with:
        ref: gitbook
            
    - name: install nodejs
      uses: actions/setup-node@v1
      
    - name: configue gitbook
      run: |
        npm install -g gitbook-cli          
        gitbook install
        npm install -g gitbook-summary
                
    - name: generate _book folder
      run: |
        book sm
        gitbook build
        cp SUMMARY.md _book
                
    - name: push _book to branch main 
      env:
        TOKEN: ${{ secrets.TOKEN }}
        REF: github.com/${{github.repository}}
        MYEMAIL: heqiangfly@163.com                  # ！！记得修改为自己github设置的邮箱
        MYNAME: ${{github.repository_owner}}          
      run: |
        cd _book
        git config --global user.email "${MYEMAIL}"
        git config --global user.name "${MYNAME}"
        git init
        git remote add origin https://${REF}
        git add . 
        git commit -m "Updated By Github Actions With Build ${{github.run_number}} of ${{github.workflow}} For Github Pages"
        git branch -M gitbook
        git push --force --quiet "https://${TOKEN}@${REF}" gitbook:main
